name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # ✅ stable version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ✅ make sure it's quoted

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            zip unzip \
            openjdk-17-jdk \
            git \
            libncurses5

      - name: Install buildozer & requirements
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK file
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: bin/*.apk
